/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExampleComponent: typeof import('./src/components/ExampleComponent.vue')['default']
    FVvGrid: typeof import('./src/components/FVvGrid.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    LeftMenuLink: typeof import('./src/components/LeftMenuLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheElementsDrawer: typeof import('./src/components/TheElementsDrawer.vue')['default']
    TheFormSettingsDrawer: typeof import('./src/components/TheFormSettingsDrawer.vue')['default']
    VVGrid: typeof import('./src/components/VVGrid.vue')['default']
  }
}
