services:
  mongo:
    image: mongo:latest
    ports:
      - ${LISTEN_MONGODB_PORT}:27017
    networks:
      - db-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admdomain}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-domain972}
    volumes:
      - ./data/mongod.conf:/etc/mongod.conf
      - ./data/mongo/data:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo
    networks:
      - db-net
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME:-admdomain}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD:-domain972}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USERNAME:-admdomain}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD:-domain972}
    ports:
      - '8081:8081'

volumes:
  app:

networks:
  db-net:
