/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthorDetail: (typeof import('./.vitepress/theme/components/blog/AuthorDetail.vue'))['default'];
    DocAfter: (typeof import('./.vitepress/theme/components/doc/DocAfter.vue'))['default'];
    Feature: (typeof import('./.vitepress/theme/components/uno/Feature.vue'))['default'];
    Post: (typeof import('./.vitepress/theme/components/blog/Post.vue'))['default'];
    PostAuthor: (typeof import('./.vitepress/theme/components/blog/PostAuthor.vue'))['default'];
    PostDetail: (typeof import('./.vitepress/theme/components/blog/PostDetail.vue'))['default'];
    PostIcon: (typeof import('./.vitepress/theme/components/blog/PostIcon.vue'))['default'];
    Posts: (typeof import('./.vitepress/theme/components/blog/Posts.vue'))['default'];
    RainbowAnimationSwitcher: (typeof import('./.vitepress/theme/components/RainbowAnimationSwitcher.vue'))['default'];
    RainbowSwitcher: (typeof import('./.vitepress/theme/components/RainbowSwitcher.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
  }
}
