/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DiagTimeLineJour: typeof import('./components/DiagTimeLineJour.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    FVvGrid: typeof import('./components/FVvGrid.vue')['default']
    LeftMenu: typeof import('./components/LeftMenu.vue')['default']
    LeftMenuLink: typeof import('./components/LeftMenuLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VVGrid: typeof import('./components/VVGrid.vue')['default']
  }
}
